### ISSUE TITLE
Getting images to fit to container

### ISSUE THREAD

**Issue by tyssen** [aFarkas/lazyflickity#2]
I came to lazyflickity for its ability lazy load images with `srcset` and `sizes` and it works great from that point of view, but I'm working on a photography portfolio website and trying to get images to fit to their container both horizontally and vertically like `background-size: contain`, rather than `cover`.

You can see an example of what I'm trying to do at http://jsfiddle.net/tyssen/td414fy8/4/

Everything is fine until you make the browser window shallower than the height of the images. Instead of the images resizing to fit, scrolling occurs.

I've tried adding `height:100%` to `.gallery` and `.gallery-cell` in conjunction with `setGallerySize: false` but then the gallery has no height at all.

Not sure if this is an issue with the implementation I've copied from lazyflickity or with Flickity itself, or whether it's actually an issue at all, but instead just something I'm not doing right, so apologies if I should be posting this somewhere else.

**Comment by aFarkas** [comment]
This is a CSS only problem. lazysizes is all about lazy loading the images and also computing the right `sizes` attribute for you, if you use `data-sizes="auto"`.

Which means you should fully solve this with the right CSS. If you want to get the `sizes` attribute calculated automatically you might need this:
https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/parent-fit

Maybe it is easier for you to accomplish your task with background images? Then you might want to use this:
https://github.com/aFarkas/lazysizes/tree/gh-pages/plugins/bgset

Here is a demo:
http://jsfiddle.net/trixta/w96o9xm5/

**Comment by tyssen** [comment]
The problem is that the `flickity-viewport` element gets a height applied to it inline which appears to be the natural height of the image regardless of scaling. So even if I get the image to fit its container, Flickity is setting the height of the container larger than the window.

It's quite possible I should be asking this question of Flickity, so happy to repost if necessary.
